// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oytvqmedvcdaaknxmgjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95dHZxbWVkdmNkYWFrbnhtZ2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDY1MTUsImV4cCI6MjA2NjMyMjUxNX0.NK5xCopPPTRyYeXXeLSbAfVEQZmJ_0uMThLRXE3OIpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);